### ISSUE TITLE
`Parser<T>.map` における `createParser` の利用はもっとシンプルにできそう

### ISSUE THREAD

**Issue by 0918nobita** [marihachi/terrario#18]
初めて issue 投げます、kodai です。

terrario 0.9.0 のライブラリ本体の定義コードを写経していて気づいたんですが、
`Parser<T>.map` の定義は

```typescript
map<U>(fn: (value: T) => U): Parser<U> {
  return createParser((input, index, children, state) => {
    const result = children[0].exec(input, state, index);
    if (!result.success) {
      return result;
    }
    return success(result.index, fn(result.value));
  }, [this]);
}
```

ではなく

```typescript
map<U>(fn: (value: T) => U): Parser<U> {
  return createParser((input, index, [], state) => {
    const result = this.exec(input, state, index); // <-- children[0] ではなく this に
    if (!result.success) {
      return result;
    }
    return success(result.index, fn(result.value));
  }); // <-- children を空に
}
```

のように `children` を空にして `this` を直接参照するほうが、
`children` として実際に何が渡されているのか確認するために視線を上下に動かしたり、 
`children` を渡し忘れても静的型チェックが通ってバグることが防げて、素直で読みやすいと思いました。

アロー関数式内での `this` はレキシカルスコープなので、
パーサの呼び出し場所等で `this` の参照先が変わることはないはずです。

fork して同様の変更を適用してテストが通ることは確認済みです。
PR 投げることもできるので検討よろしくお願いしますm(_ _)m

ブランチ：https://github.com/0918nobita/terrario/tree/simplify-use-of-createParser

**Comment by marihachi** [comment]
issueありがとうございます。

子パーサーをchildrenに一旦入れてるのは意図的なものです！
パーサー呼び出しをハードコードするのではなく、パーサーの親子関係を明確にした方が今後の拡張がしやすいだろうという判断でこのようになってます(これまではthisで呼んでました)。
例えば子パーサーが何らかの状態を保持して最後に親パーサーからその状態を利用して結果として返すようなことが可能になると思っています。今のところ使用していませんが。

**Comment by 0918nobita** [comment]
> パーサーの親子関係を明確にした方が今後の拡張がしやすい

なるほど

確認・返信ありがとうございました
