### ISSUE TITLE
`==` / `!=` よりも `===` / `!==` 使うのがオススメです

### ISSUE THREAD

**Issue by 0918nobita** [marihachi/terrario#19]
`===` / `!==` のほうが暗黙的な型変換が行われずバグが減らせてオススメです。

ブランチ：https://github.com/0918nobita/terrario/tree/triple-equals

**Comment by marihachi** [comment]
厳密に比較する必要がなければ大丈夫かなと思っています。
型チェックはTypeScriptによって保証されているので、問題があるとすれば実行時の話ですかね...

**Comment by marihachi** [comment]
related to #9

**Comment by marihachi** [comment]
基本的に厳密等価比較を使うことにしようと思います。
ただしnullとの比較は引き続き等価比較を使用します。
